### ISSUE TITLE
RecordLayer length doubt

### ISSUE THREAD

**Issue by lespla** [tintinweb/scapy-ssl_tls#45] opened 2015-07-21 06:36 UTC
Hello,
When I add a SNI with length of 65000 bytes, I only see a RecordLayer but I read TLS RFC(5246), I think that they say that the maximum size of RecordLayer is 2 ^14 (16384 bytes).
Is it a bug or is it available  to use bigger size than 16384?
BR

**Comment by tintinweb** [comment] 2015-07-21 07:24
It is not a bug.
[RFC-5246 (TLS1.2)](https://tools.ietf.org/html/rfc5246#section-6.2.1) restricts the maximum fragment size to 2^14 bytes. scapy-ssl_tls layers have no intention to artificially limit you to this length even-though it is not RFC compliant. We allow you to create records up to the maximum possible size (USHRT_MAX=2^16-1). if you want to transport SNI entries larger than 2^14 bytes (record length) you'll have to fragment the resulting layer into multiple <= 2^14 bytes records. see #43

**Comment by alexmgr** [comment] 2015-07-23 04:19
As Tin mentioned, this is not a bug. I added fragmentation support in PR #46. It's still up to you to fragment on the 2^14 boundary though (using `tls_fragment_payload()` or `fragment()`)

**Comment by alexmgr** [comment] 2015-07-27 18:08
Merged #46. We know raise exceptions when fragmentation is needed. Closing.

**Closed by alexmgr** 2015-07-27 18:08 UTC
Labels: question
